FROM golang:1.22 as builder

ARG CGO_ENABLED=0
WORKDIR /server

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build

FROM scratch
COPY --from=builder /app/server /server
ENTRYPOINT ["/server"]